[project]
name = "atompy"
version = "5.0.0-dev" # also update _version.py
authors = [{ name = "Max Kircher", email = "kircher@atom.uni-frankfurt.de" }]
description = """
    A collection of utility functions to create plots and do
    analysis.
"""
readme = "README.md"
requires-python = ">=3.10"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: MIT",
    "Operating System :: OS Independent",
]
dependencies = [
    "numpy",
    "matplotlib",
    "uproot",
    "scipy",
    "mplutils @ https://github.com/frekm/mpl-utils/archive/refs/tags/v0.1.0.zip"
]

[project.urls]
"Repository" = "https://github.com/frekm/atompy"
"Documentation" = "https://atomphys-atompy.readthedocs.io/en/latest/"
